import { StyleSheet } from "react-native";

export const theme = {
  colors: {
    background: "#376f6c",
    surface: "#f3f4f3",
    drawer: "#2f5f55",
    accent: "#2f8b73",
    text: "#1f2f2b",
    textMuted: "#6d7f7b",
    border: "#c7d2cf",
    icon: "#2f5f55",
    danger: "#d65b5b",
  },
};

export default StyleSheet.create({
  container: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    width: "100%",
    backgroundColor: theme.colors.background,
  },

  titulo: {
    fontSize: 28,
    fontWeight: "bold",
  },
  input: {
    color: "white",
    backgroundColor: "gray",
    padding: 1,
    height: 20,
    width: 300,
    marginTop: 15,
  },
  inputcontainer: {
    height: 180,
    marginBottom: "15%",
    marginTop: "5%",
    borderRadius: 10,
    backgroundColor: "white",
    padding: 15,
    height: 380,
    borderRadius: 12,
  },
  // inputcontainerlog: {
  //   height: 350,
  //   width: 350,
  //   marginBottom: "5%",
  //   marginTop: "5%",
  //   borderRadius: 10,
  //   backgroundColor: "white",
  //   padding: 40,
  //   borderRadius: 12,
  // },
  form: {
    flex: 1,
    backgroundColor: theme.colors.surface,
    padding: 20,
    borderRadius: 10,
    margin: 15,
    alignItems: "center",
    justifyContent: "center",
  },
  botaoLog: {
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: theme.colors.accent,
    pisition: "absoulute",
    fontSize: 30,
    borderRadius: 15,
    padding: 5,
    marginTop: 10,
    width: "60%",
    height: "5%",
  },
  // botaoCad: {
  //   alignItems: "center",
  //   justifyContent: "center",
  //   backgroundColor: theme.colors.accent,
  //   position: "absoulute",
  //   fontSize: 30,
  //   borderRadius: 15,
  //   padding: 5,
  //   width: "60%",
  //   height: "5%",
  // },
  // botaoOp: {
  //   alignItems: "center",
  //   justifyContent: "center",
  //   backgroundColor: "white",
  //   borderColor: "#007BFF",
  //   borderWidth: 2,
  //   borderRadius: 15,
  //   position: "absoulute",
  //   fontSize: 30,
  //   borderRadius: 15,
  //   padding: 5,
  //   marginTop: 10,
  //   width: "60%",
  //   height: "5%",
  // },
  botaoList: {
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: theme.colors.accent,
    position: "absoulute",
    fontSize: 30,
    borderRadius: 15,
    padding: 5,
    marginTop: 60,
    width: "60%",
    height: "5%",
  },

  imagem: {
    height: 200,
  },
  logo: {
    justifyContent: "space-evenly",
    alignItems: "flex-start",
  },
  inputPicker: {
    backgroundColor: "gray",
    color: "white",
    marginTop: 20,
    paddingLeft: 8,
    marginBottom: 20,
    borderRadius: 2,
  },
  textPicker: {
    color: "white",
  },
  row: {
    flexDirection: "row",
    justifyContent: "space-between", // espaça as colunas
    alignItems: "center",
    width: "100%", //pra dxa alinnhado c o titulo
    alignSelf: "center",
    marginVertical: 4,
  },

  card: {
    width: "92%",
    backgroundColor: theme.colors.surface,
    borderRadius: 16,
    padding: 14,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.12,
    shadowRadius: 8,
    elevation: 4,
    marginVertical: 8,
  },

  title: {
    fontSize: 22,
    fontWeight: "800",
    color: theme.colors.text,
    marginBottom: 8,
    alignSelf: "flex-start",
    marginLeft: 8,
  },

  column: {
    flex: 1,
    alignItems: "center",
    backgroundColor: "gray",
    marginHorizontal: 3,
    borderRadius: 4,
    paddingVertical: 6,
    marginTop: 10,
  },
  inputPicker: {
    marginBottom: 20,
    backgroundColor: theme.colors.surface,
    paddingLeft: 8,
  },
  inputPickerdata: {
    marginBottom: 20,
    backgroundColor: "gray",
  },
  inputPickersala: {
    marginBottom: 10,
    backgroundColor: "gray",
    padding: 6,
    marginTop: 20,
  },
  inputView: {
    width: "55%",
    marginBottom: 20,
  },

  tabelatext: {
    flex: 1,
    backgroundColor: "white",
    borderRadius: 15,
    justifyContent: "center",
    textAlign: "center",
    fontWeight: "bold",
    fontSize: 15,
    color: theme.colors.text,
    marginLeft: 40,
    marginRight: 40,
    marginTop: 10,
    padding: 10,
    borderColor: theme.colors.border,
    borderWidth: 3,
  },
  tableHeader: {
    flexDirection: "row",
    backgroundColor: theme.colors.drawer,
    paddingVertical: 10,
    paddingHorizontal: 8,
    borderTopLeftRadius: 10,
    borderTopRightRadius: 10,
    width: "100%",
    justifyContent: "space-between",
    marginTop: 6,
  },
  tableRow: {
    flexDirection: "row",
    alignItems: "center",
    paddingVertical: 12,
    paddingHorizontal: 10,
    borderBottomWidth: 0,
  },
  cell: {
    flex: 1,
    paddingHorizontal: 6,
  },
  headerText: {
    fontWeight: "700",
    color: "#e9f3f0",
  },
  checkboxCell: {
    width: 70,
    alignItems: "center",
  },
  header: {
    width: "100%",
    paddingTop: 26,
    paddingBottom: 18,
    paddingHorizontal: 18,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    backgroundColor: "transparent",
  },
  headerBackButton: {
    width: 42,
    height: 42,
    alignItems: "center",
    justifyContent: "center",
    marginRight: 8,
  },
  headerTitle: {
    fontSize: 24,
    fontWeight: "800",
    color: "#f4f6f5",
  },
  headerRightButton: {
    width: 38,
    height: 38,
    alignItems: "center",
    justifyContent: "center",
  },
  drawerTab: {
    position: "absolute",
    left: 0,
    top: "50%",
    transform: [{ translateY: -20 }],
    backgroundColor: theme.colors.surface,
    paddingVertical: 8,
    paddingHorizontal: 6,
    borderTopRightRadius: 10,
    borderBottomRightRadius: 10,
    elevation: 4,
  },
  drawerTabText: {
    color: theme.colors.text,
    fontSize: 18,
    fontWeight: "600",
  },
  primaryButton: {
    backgroundColor: theme.colors.accent,
    paddingVertical: 12,
    paddingHorizontal: 18,
    borderRadius: 16,
    alignItems: "center",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.12,
    shadowRadius: 6,
    elevation: 2,
  },
  secondButton: {
    backgroundColor: "#e9eeed",
    paddingVertical: 10,
    paddingHorizontal: 16,
    borderRadius: 16,
    alignItems: "center",
  },
  primaryButtonText: {
    color: "#fff",
    fontWeight: "700",
  },
  secondButtonText: {
    color: theme.colors.accent,
    fontWeight: "700",
  },
  formCard: {
    width: "92%",
    backgroundColor: theme.colors.surface,
    borderRadius: 12,
    padding: 15,
    marginVertical: 12,
    elevation: 2,
  },
  inputOutlined: {  
    borderRadius: 14,
    backgroundColor: "#e9eeed",
    color: "#2a3f3b",
    fontSize: 14,
    marginBottom: 12,
  },
  selectWrapper: {
    borderRadius: 14,
    borderWidth: 1,
    borderColor: theme.colors.border,
    overflow: "hidden",
    marginBottom: 10,
    backgroundColor: "#e9eeed",
  },
  formActions: {
    width: "100%",
    alignItems: "center",
    marginTop: 8,
  },
  drawerHeader: {
    padding: 16,
    backgroundColor: theme.colors.drawer,
    flexDirection: "row",
    alignItems: "center",
  },
  drawerEmail: {
    color: theme.colors.text,
    fontSize: 12,
  },
  menuGrid: {
    flex: 1,
    flexDirection: "row",
    flexWrap: "wrap",
    justifyContent: "space-between",
    paddingHorizontal: 12,
    paddingVertical: 16,
    gap: 12,
  },
  menuCard: {
    width: "48%",
    backgroundColor: theme.colors.surface,
    borderRadius: 16,
    padding: 12,
    alignItems: "center",
    justifyContent: "center",
    elevation: 4,
    minHeight: 110,
  },
  menuCardIcon: {
    fontSize: 32,
    marginBottom: 8,
    color: theme.colors.textMuted,
  },
  menuCardText: {
    fontWeight: "600",
    color: theme.colors.text,
    fontSize: 12,
    textAlign: "center",
  },
  listCard: {
    width: "94%",
    alignSelf: "center",
    backgroundColor: theme.colors.surface,
    borderRadius: 16,
    paddingHorizontal: 16,
    paddingBottom: 12,
    paddingTop: 12,
    marginVertical: 6,
    elevation: 3,
    borderLeftWidth: 0,
  },
  listCardText: {
    fontWeight: "600",
    color: theme.colors.text,
    fontSize: 14,
    marginRight: 10,
  },
  listCardSubtext: {
    fontSize: 12,
    color: theme.colors.textMuted,
    marginRight: 10,
    padding:3
  },
  listContainer: {
    flex: 1,
    alignItems: "center",
    width: "100%",
    paddingBottom: 20,
  },
  filterCard: {
    width: "92%",
    backgroundColor: theme.colors.surface,
    borderRadius: 12,
    padding: 12,
    elevation: 2,
    marginBottom: 12,
  },
  tabela: {
    justifyContent: "center",
    alignItems: "center",
    marginLeft: "22",
    marginRight: "22",
  },
  touch: {
    backgroundColor: "gray",
  },
 tableContainer: {
  width: "100%",
  paddingVertical: 10,
  paddingHorizontal: 16,
},
 tableHeaderRow: {
  flexDirection: "row",
  backgroundColor: theme.colors.drawer,
  paddingVertical: 12,
  marginHorizontal:0,
  borderTopLeftRadius: 10,
  borderTopRightRadius: 10,
  width: "100%",
  alignSelf: "center",
},
tableHeaderText: {
  
  paddingHorizontal: 8,
  fontWeight: "700",
  color: "#ffffff",
  fontSize: 13,
  textAlign: "center",
},
  tableDataRow: {
    flexDirection: "row",
    backgroundColor: theme.colors.surface,
    paddingVertical: 12,
    paddingHorizontal: 10,
    borderBottomWidth: 0,
    alignItems: "center",
    width: "100%",
    alignSelf: "center",
    verticalAlign: "middle",
    textAlign: "center",
    justifyContent: "center",
  },
  tableDataCell: {
  flex: 1,
  fontSize: 15,
  color: theme.colors.text,
  textAlign: "center",
  paddingHorizontal: 21,
  verticalAlign: "middle",
  alignItems: "center",
},
  lastTableDataCell: {
  
  fontSize: 15,
  color: theme.colors.text,
  textAlign: "center",
  paddingHorizontal: 8
},
  tableColumnText: {
    flex: 0,
    width: "100%",
    textAlign: "center",
    paddingHorizontal: 8,
  },
  tableColumnCell: {
    backgroundColor: theme.colors.surface,
    paddingVertical: 12,
    paddingHorizontal: 10,
    borderBottomWidth: 0,
    alignItems: "center",
    justifyContent: "center",
    minHeight: 52,
  },
  tableColumnDivider: {
    borderRightWidth: 1,
    borderRightColor: theme.colors.border,
  },
  tableLastRow: {
    borderBottomWidth: 0,
  },
  tableActionButton: {
    backgroundColor: theme.colors.accent,
    borderRadius: 12,
    alignItems: "center",
    alignSelf: "stretch",
    justifyContent: "center",
    minHeight: 54,
    paddingVertical: 10,
    paddingHorizontal: 14,
  },
  tableActionButtonText: {
    color: "#fff",
    fontWeight: "700",
    fontSize: 15,
  },

  tableEmptyContainer: {
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 40,
  },
  tableEmptyText: {
    color: "#fff",
    fontSize: 14,
  },
});
